// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server.renovation.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Server {

  /// <summary>Holder for reflection information generated from server.renovation.proto</summary>
  public static partial class ServerRenovationReflection {

    #region Descriptor
    /// <summary>File descriptor for server.renovation.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServerRenovationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdzZXJ2ZXIucmVub3ZhdGlvbi5wcm90bxIGc2VydmVyGgxjb21tb24ucHJv",
            "dG8iZAoSUmVub3ZhdGlvblRhc2tJbmZvEhQKDHRhc2tSZWNvcmRJZBgBIAIo",
            "CRIUCgx0YXNrQ29uZmlnSWQYAiACKAkSEAoIdGFza05hbWUYAyACKAkSEAoI",
            "cmVzb3VyY2UYBCACKAkigAEKFFJlbm92YXRpb25SZXdhcmRJbmZvEhkKEWN1",
            "clJld2FyZENvbmZpZ0lkGAEgAigJEhIKCmN1clRhc2tOdW0YAiACKAUSEgoK",
            "bWF4VGFza051bRgDIAIoBRIlCgpyZXdhcmRMaXN0GAQgAygLMhEuY29tbW9u",
            "Lkdvb2RzSXRlbSLFAgoaRmluaXNoUmVub3ZhdGlvblRhc2tSZXN1bHQSDAoE",
            "Y29kZRgBIAIoBRILCgNtc2cYAiACKAkSNwoEZGF0YRgDIAEoCzIpLnNlcnZl",
            "ci5GaW5pc2hSZW5vdmF0aW9uVGFza1Jlc3VsdC5SZXN1bHQa0gEKBlJlc3Vs",
            "dBIoCg1jb3N0R29vZHNMaXN0GAEgAygLMhEuY29tbW9uLkdvb2RzSXRlbRIq",
            "Cg9yZXdhcmRHb29kc0xpc3QYAiADKAsyES5jb21tb24uR29vZHNJdGVtEjYK",
            "EnJlbm92YXRpb25UYXNrSW5mbxgDIAIoCzIaLnNlcnZlci5SZW5vdmF0aW9u",
            "VGFza0luZm8SOgoUcmVub3ZhdGlvblJld2FyZEluZm8YBCACKAsyHC5zZXJ2",
            "ZXIuUmVub3ZhdGlvblJld2FyZEluZm8itAEKE1Jlbm92YXRpb25TdG9yZUlu",
            "Zm8SFQoNc3RvcmVDb25maWdJZBgBIAIoCRIVCg1nb29kc0NvbmZpZ0lkGAIg",
            "AigJEhEKCXN0b3JlVHlwZRgDIAIoCRIWCg5jdXJFeGNoYW5nZU51bRgEIAIo",
            "BRIWCg5tYXhFeGNoYW5nZU51bRgFIAIoBRIsChFleGNoYW5nZU1hdGVyaWFs",
            "cxgGIAMoCzIRLmNvbW1vbi5Hb29kc0l0ZW0iZQodRXhjaGFuZ2VSZW5vdmF0",
            "aW9uU3RvcmVSZXN1bHQSDAoEY29kZRgBIAIoBRILCgNtc2cYAiACKAkSKQoE",
            "ZGF0YRgDIAEoCzIbLnNlcnZlci5SZW5vdmF0aW9uU3RvcmVJbmZvImUKHkNo",
            "b29zZVJlbm92YXRpb25SZXNvdXJjZVJlc3VsdBIMCgRjb2RlGAEgAigFEgsK",
            "A21zZxgCIAIoCRIoCgRkYXRhGAMgASgLMhouc2VydmVyLlJlbm92YXRpb25U",
            "YXNrSW5mbw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Server.RenovationTaskInfo), global::Server.RenovationTaskInfo.Parser, new[]{ "TaskRecordId", "TaskConfigId", "TaskName", "Resource" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Server.RenovationRewardInfo), global::Server.RenovationRewardInfo.Parser, new[]{ "CurRewardConfigId", "CurTaskNum", "MaxTaskNum", "RewardList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Server.FinishRenovationTaskResult), global::Server.FinishRenovationTaskResult.Parser, new[]{ "Code", "Msg", "Data" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Server.FinishRenovationTaskResult.Types.Result), global::Server.FinishRenovationTaskResult.Types.Result.Parser, new[]{ "CostGoodsList", "RewardGoodsList", "RenovationTaskInfo", "RenovationRewardInfo" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Server.RenovationStoreInfo), global::Server.RenovationStoreInfo.Parser, new[]{ "StoreConfigId", "GoodsConfigId", "StoreType", "CurExchangeNum", "MaxExchangeNum", "ExchangeMaterials" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Server.ExchangeRenovationStoreResult), global::Server.ExchangeRenovationStoreResult.Parser, new[]{ "Code", "Msg", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Server.ChooseRenovationResourceResult), global::Server.ChooseRenovationResourceResult.Parser, new[]{ "Code", "Msg", "Data" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RenovationTaskInfo : pb::IMessage<RenovationTaskInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RenovationTaskInfo> _parser = new pb::MessageParser<RenovationTaskInfo>(() => new RenovationTaskInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RenovationTaskInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server.ServerRenovationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RenovationTaskInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RenovationTaskInfo(RenovationTaskInfo other) : this() {
      taskRecordId_ = other.taskRecordId_;
      taskConfigId_ = other.taskConfigId_;
      taskName_ = other.taskName_;
      resource_ = other.resource_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RenovationTaskInfo Clone() {
      return new RenovationTaskInfo(this);
    }

    /// <summary>Field number for the "taskRecordId" field.</summary>
    public const int TaskRecordIdFieldNumber = 1;
    private readonly static string TaskRecordIdDefaultValue = "";

    private string taskRecordId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaskRecordId {
      get { return taskRecordId_ ?? TaskRecordIdDefaultValue; }
      set {
        taskRecordId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "taskRecordId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTaskRecordId {
      get { return taskRecordId_ != null; }
    }
    /// <summary>Clears the value of the "taskRecordId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTaskRecordId() {
      taskRecordId_ = null;
    }

    /// <summary>Field number for the "taskConfigId" field.</summary>
    public const int TaskConfigIdFieldNumber = 2;
    private readonly static string TaskConfigIdDefaultValue = "";

    private string taskConfigId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaskConfigId {
      get { return taskConfigId_ ?? TaskConfigIdDefaultValue; }
      set {
        taskConfigId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "taskConfigId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTaskConfigId {
      get { return taskConfigId_ != null; }
    }
    /// <summary>Clears the value of the "taskConfigId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTaskConfigId() {
      taskConfigId_ = null;
    }

    /// <summary>Field number for the "taskName" field.</summary>
    public const int TaskNameFieldNumber = 3;
    private readonly static string TaskNameDefaultValue = "";

    private string taskName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaskName {
      get { return taskName_ ?? TaskNameDefaultValue; }
      set {
        taskName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "taskName" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTaskName {
      get { return taskName_ != null; }
    }
    /// <summary>Clears the value of the "taskName" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTaskName() {
      taskName_ = null;
    }

    /// <summary>Field number for the "resource" field.</summary>
    public const int ResourceFieldNumber = 4;
    private readonly static string ResourceDefaultValue = "";

    private string resource_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Resource {
      get { return resource_ ?? ResourceDefaultValue; }
      set {
        resource_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "resource" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasResource {
      get { return resource_ != null; }
    }
    /// <summary>Clears the value of the "resource" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResource() {
      resource_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RenovationTaskInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RenovationTaskInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TaskRecordId != other.TaskRecordId) return false;
      if (TaskConfigId != other.TaskConfigId) return false;
      if (TaskName != other.TaskName) return false;
      if (Resource != other.Resource) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasTaskRecordId) hash ^= TaskRecordId.GetHashCode();
      if (HasTaskConfigId) hash ^= TaskConfigId.GetHashCode();
      if (HasTaskName) hash ^= TaskName.GetHashCode();
      if (HasResource) hash ^= Resource.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasTaskRecordId) {
        output.WriteRawTag(10);
        output.WriteString(TaskRecordId);
      }
      if (HasTaskConfigId) {
        output.WriteRawTag(18);
        output.WriteString(TaskConfigId);
      }
      if (HasTaskName) {
        output.WriteRawTag(26);
        output.WriteString(TaskName);
      }
      if (HasResource) {
        output.WriteRawTag(34);
        output.WriteString(Resource);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasTaskRecordId) {
        output.WriteRawTag(10);
        output.WriteString(TaskRecordId);
      }
      if (HasTaskConfigId) {
        output.WriteRawTag(18);
        output.WriteString(TaskConfigId);
      }
      if (HasTaskName) {
        output.WriteRawTag(26);
        output.WriteString(TaskName);
      }
      if (HasResource) {
        output.WriteRawTag(34);
        output.WriteString(Resource);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasTaskRecordId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskRecordId);
      }
      if (HasTaskConfigId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskConfigId);
      }
      if (HasTaskName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskName);
      }
      if (HasResource) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Resource);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RenovationTaskInfo other) {
      if (other == null) {
        return;
      }
      if (other.HasTaskRecordId) {
        TaskRecordId = other.TaskRecordId;
      }
      if (other.HasTaskConfigId) {
        TaskConfigId = other.TaskConfigId;
      }
      if (other.HasTaskName) {
        TaskName = other.TaskName;
      }
      if (other.HasResource) {
        Resource = other.Resource;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TaskRecordId = input.ReadString();
            break;
          }
          case 18: {
            TaskConfigId = input.ReadString();
            break;
          }
          case 26: {
            TaskName = input.ReadString();
            break;
          }
          case 34: {
            Resource = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TaskRecordId = input.ReadString();
            break;
          }
          case 18: {
            TaskConfigId = input.ReadString();
            break;
          }
          case 26: {
            TaskName = input.ReadString();
            break;
          }
          case 34: {
            Resource = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RenovationRewardInfo : pb::IMessage<RenovationRewardInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RenovationRewardInfo> _parser = new pb::MessageParser<RenovationRewardInfo>(() => new RenovationRewardInfo());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RenovationRewardInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server.ServerRenovationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RenovationRewardInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RenovationRewardInfo(RenovationRewardInfo other) : this() {
      _hasBits0 = other._hasBits0;
      curRewardConfigId_ = other.curRewardConfigId_;
      curTaskNum_ = other.curTaskNum_;
      maxTaskNum_ = other.maxTaskNum_;
      rewardList_ = other.rewardList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RenovationRewardInfo Clone() {
      return new RenovationRewardInfo(this);
    }

    /// <summary>Field number for the "curRewardConfigId" field.</summary>
    public const int CurRewardConfigIdFieldNumber = 1;
    private readonly static string CurRewardConfigIdDefaultValue = "";

    private string curRewardConfigId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CurRewardConfigId {
      get { return curRewardConfigId_ ?? CurRewardConfigIdDefaultValue; }
      set {
        curRewardConfigId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "curRewardConfigId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCurRewardConfigId {
      get { return curRewardConfigId_ != null; }
    }
    /// <summary>Clears the value of the "curRewardConfigId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCurRewardConfigId() {
      curRewardConfigId_ = null;
    }

    /// <summary>Field number for the "curTaskNum" field.</summary>
    public const int CurTaskNumFieldNumber = 2;
    private readonly static int CurTaskNumDefaultValue = 0;

    private int curTaskNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CurTaskNum {
      get { if ((_hasBits0 & 1) != 0) { return curTaskNum_; } else { return CurTaskNumDefaultValue; } }
      set {
        _hasBits0 |= 1;
        curTaskNum_ = value;
      }
    }
    /// <summary>Gets whether the "curTaskNum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCurTaskNum {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "curTaskNum" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCurTaskNum() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "maxTaskNum" field.</summary>
    public const int MaxTaskNumFieldNumber = 3;
    private readonly static int MaxTaskNumDefaultValue = 0;

    private int maxTaskNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxTaskNum {
      get { if ((_hasBits0 & 2) != 0) { return maxTaskNum_; } else { return MaxTaskNumDefaultValue; } }
      set {
        _hasBits0 |= 2;
        maxTaskNum_ = value;
      }
    }
    /// <summary>Gets whether the "maxTaskNum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMaxTaskNum {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "maxTaskNum" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMaxTaskNum() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "rewardList" field.</summary>
    public const int RewardListFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Common.GoodsItem> _repeated_rewardList_codec
        = pb::FieldCodec.ForMessage(34, global::Common.GoodsItem.Parser);
    private readonly pbc::RepeatedField<global::Common.GoodsItem> rewardList_ = new pbc::RepeatedField<global::Common.GoodsItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Common.GoodsItem> RewardList {
      get { return rewardList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RenovationRewardInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RenovationRewardInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CurRewardConfigId != other.CurRewardConfigId) return false;
      if (CurTaskNum != other.CurTaskNum) return false;
      if (MaxTaskNum != other.MaxTaskNum) return false;
      if(!rewardList_.Equals(other.rewardList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCurRewardConfigId) hash ^= CurRewardConfigId.GetHashCode();
      if (HasCurTaskNum) hash ^= CurTaskNum.GetHashCode();
      if (HasMaxTaskNum) hash ^= MaxTaskNum.GetHashCode();
      hash ^= rewardList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCurRewardConfigId) {
        output.WriteRawTag(10);
        output.WriteString(CurRewardConfigId);
      }
      if (HasCurTaskNum) {
        output.WriteRawTag(16);
        output.WriteInt32(CurTaskNum);
      }
      if (HasMaxTaskNum) {
        output.WriteRawTag(24);
        output.WriteInt32(MaxTaskNum);
      }
      rewardList_.WriteTo(output, _repeated_rewardList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCurRewardConfigId) {
        output.WriteRawTag(10);
        output.WriteString(CurRewardConfigId);
      }
      if (HasCurTaskNum) {
        output.WriteRawTag(16);
        output.WriteInt32(CurTaskNum);
      }
      if (HasMaxTaskNum) {
        output.WriteRawTag(24);
        output.WriteInt32(MaxTaskNum);
      }
      rewardList_.WriteTo(ref output, _repeated_rewardList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCurRewardConfigId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurRewardConfigId);
      }
      if (HasCurTaskNum) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurTaskNum);
      }
      if (HasMaxTaskNum) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxTaskNum);
      }
      size += rewardList_.CalculateSize(_repeated_rewardList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RenovationRewardInfo other) {
      if (other == null) {
        return;
      }
      if (other.HasCurRewardConfigId) {
        CurRewardConfigId = other.CurRewardConfigId;
      }
      if (other.HasCurTaskNum) {
        CurTaskNum = other.CurTaskNum;
      }
      if (other.HasMaxTaskNum) {
        MaxTaskNum = other.MaxTaskNum;
      }
      rewardList_.Add(other.rewardList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CurRewardConfigId = input.ReadString();
            break;
          }
          case 16: {
            CurTaskNum = input.ReadInt32();
            break;
          }
          case 24: {
            MaxTaskNum = input.ReadInt32();
            break;
          }
          case 34: {
            rewardList_.AddEntriesFrom(input, _repeated_rewardList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CurRewardConfigId = input.ReadString();
            break;
          }
          case 16: {
            CurTaskNum = input.ReadInt32();
            break;
          }
          case 24: {
            MaxTaskNum = input.ReadInt32();
            break;
          }
          case 34: {
            rewardList_.AddEntriesFrom(ref input, _repeated_rewardList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FinishRenovationTaskResult : pb::IMessage<FinishRenovationTaskResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FinishRenovationTaskResult> _parser = new pb::MessageParser<FinishRenovationTaskResult>(() => new FinishRenovationTaskResult());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FinishRenovationTaskResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server.ServerRenovationReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishRenovationTaskResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishRenovationTaskResult(FinishRenovationTaskResult other) : this() {
      _hasBits0 = other._hasBits0;
      code_ = other.code_;
      msg_ = other.msg_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FinishRenovationTaskResult Clone() {
      return new FinishRenovationTaskResult(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private readonly static int CodeDefaultValue = 0;

    private int code_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { if ((_hasBits0 & 1) != 0) { return code_; } else { return CodeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        code_ = value;
      }
    }
    /// <summary>Gets whether the "code" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCode {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "code" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCode() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 2;
    private readonly static string MsgDefaultValue = "";

    private string msg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_ ?? MsgDefaultValue; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "msg" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMsg {
      get { return msg_ != null; }
    }
    /// <summary>Clears the value of the "msg" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMsg() {
      msg_ = null;
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private global::Server.FinishRenovationTaskResult.Types.Result data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Server.FinishRenovationTaskResult.Types.Result Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FinishRenovationTaskResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FinishRenovationTaskResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Msg != other.Msg) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCode) hash ^= Code.GetHashCode();
      if (HasMsg) hash ^= Msg.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCode) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (HasMsg) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCode) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (HasMsg) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCode) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (HasMsg) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FinishRenovationTaskResult other) {
      if (other == null) {
        return;
      }
      if (other.HasCode) {
        Code = other.Code;
      }
      if (other.HasMsg) {
        Msg = other.Msg;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Server.FinishRenovationTaskResult.Types.Result();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::Server.FinishRenovationTaskResult.Types.Result();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::Server.FinishRenovationTaskResult.Types.Result();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the FinishRenovationTaskResult message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class Result : pb::IMessage<Result>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Result> _parser = new pb::MessageParser<Result>(() => new Result());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Result> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Server.FinishRenovationTaskResult.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Result() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Result(Result other) : this() {
          costGoodsList_ = other.costGoodsList_.Clone();
          rewardGoodsList_ = other.rewardGoodsList_.Clone();
          renovationTaskInfo_ = other.renovationTaskInfo_ != null ? other.renovationTaskInfo_.Clone() : null;
          renovationRewardInfo_ = other.renovationRewardInfo_ != null ? other.renovationRewardInfo_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Result Clone() {
          return new Result(this);
        }

        /// <summary>Field number for the "costGoodsList" field.</summary>
        public const int CostGoodsListFieldNumber = 1;
        private static readonly pb::FieldCodec<global::Common.GoodsItem> _repeated_costGoodsList_codec
            = pb::FieldCodec.ForMessage(10, global::Common.GoodsItem.Parser);
        private readonly pbc::RepeatedField<global::Common.GoodsItem> costGoodsList_ = new pbc::RepeatedField<global::Common.GoodsItem>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Common.GoodsItem> CostGoodsList {
          get { return costGoodsList_; }
        }

        /// <summary>Field number for the "rewardGoodsList" field.</summary>
        public const int RewardGoodsListFieldNumber = 2;
        private static readonly pb::FieldCodec<global::Common.GoodsItem> _repeated_rewardGoodsList_codec
            = pb::FieldCodec.ForMessage(18, global::Common.GoodsItem.Parser);
        private readonly pbc::RepeatedField<global::Common.GoodsItem> rewardGoodsList_ = new pbc::RepeatedField<global::Common.GoodsItem>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Common.GoodsItem> RewardGoodsList {
          get { return rewardGoodsList_; }
        }

        /// <summary>Field number for the "renovationTaskInfo" field.</summary>
        public const int RenovationTaskInfoFieldNumber = 3;
        private global::Server.RenovationTaskInfo renovationTaskInfo_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Server.RenovationTaskInfo RenovationTaskInfo {
          get { return renovationTaskInfo_; }
          set {
            renovationTaskInfo_ = value;
          }
        }

        /// <summary>Field number for the "renovationRewardInfo" field.</summary>
        public const int RenovationRewardInfoFieldNumber = 4;
        private global::Server.RenovationRewardInfo renovationRewardInfo_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Server.RenovationRewardInfo RenovationRewardInfo {
          get { return renovationRewardInfo_; }
          set {
            renovationRewardInfo_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Result);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Result other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!costGoodsList_.Equals(other.costGoodsList_)) return false;
          if(!rewardGoodsList_.Equals(other.rewardGoodsList_)) return false;
          if (!object.Equals(RenovationTaskInfo, other.RenovationTaskInfo)) return false;
          if (!object.Equals(RenovationRewardInfo, other.RenovationRewardInfo)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= costGoodsList_.GetHashCode();
          hash ^= rewardGoodsList_.GetHashCode();
          if (renovationTaskInfo_ != null) hash ^= RenovationTaskInfo.GetHashCode();
          if (renovationRewardInfo_ != null) hash ^= RenovationRewardInfo.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          costGoodsList_.WriteTo(output, _repeated_costGoodsList_codec);
          rewardGoodsList_.WriteTo(output, _repeated_rewardGoodsList_codec);
          if (renovationTaskInfo_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(RenovationTaskInfo);
          }
          if (renovationRewardInfo_ != null) {
            output.WriteRawTag(34);
            output.WriteMessage(RenovationRewardInfo);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          costGoodsList_.WriteTo(ref output, _repeated_costGoodsList_codec);
          rewardGoodsList_.WriteTo(ref output, _repeated_rewardGoodsList_codec);
          if (renovationTaskInfo_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(RenovationTaskInfo);
          }
          if (renovationRewardInfo_ != null) {
            output.WriteRawTag(34);
            output.WriteMessage(RenovationRewardInfo);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          size += costGoodsList_.CalculateSize(_repeated_costGoodsList_codec);
          size += rewardGoodsList_.CalculateSize(_repeated_rewardGoodsList_codec);
          if (renovationTaskInfo_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(RenovationTaskInfo);
          }
          if (renovationRewardInfo_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(RenovationRewardInfo);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Result other) {
          if (other == null) {
            return;
          }
          costGoodsList_.Add(other.costGoodsList_);
          rewardGoodsList_.Add(other.rewardGoodsList_);
          if (other.renovationTaskInfo_ != null) {
            if (renovationTaskInfo_ == null) {
              RenovationTaskInfo = new global::Server.RenovationTaskInfo();
            }
            RenovationTaskInfo.MergeFrom(other.RenovationTaskInfo);
          }
          if (other.renovationRewardInfo_ != null) {
            if (renovationRewardInfo_ == null) {
              RenovationRewardInfo = new global::Server.RenovationRewardInfo();
            }
            RenovationRewardInfo.MergeFrom(other.RenovationRewardInfo);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                costGoodsList_.AddEntriesFrom(input, _repeated_costGoodsList_codec);
                break;
              }
              case 18: {
                rewardGoodsList_.AddEntriesFrom(input, _repeated_rewardGoodsList_codec);
                break;
              }
              case 26: {
                if (renovationTaskInfo_ == null) {
                  RenovationTaskInfo = new global::Server.RenovationTaskInfo();
                }
                input.ReadMessage(RenovationTaskInfo);
                break;
              }
              case 34: {
                if (renovationRewardInfo_ == null) {
                  RenovationRewardInfo = new global::Server.RenovationRewardInfo();
                }
                input.ReadMessage(RenovationRewardInfo);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                costGoodsList_.AddEntriesFrom(ref input, _repeated_costGoodsList_codec);
                break;
              }
              case 18: {
                rewardGoodsList_.AddEntriesFrom(ref input, _repeated_rewardGoodsList_codec);
                break;
              }
              case 26: {
                if (renovationTaskInfo_ == null) {
                  RenovationTaskInfo = new global::Server.RenovationTaskInfo();
                }
                input.ReadMessage(RenovationTaskInfo);
                break;
              }
              case 34: {
                if (renovationRewardInfo_ == null) {
                  RenovationRewardInfo = new global::Server.RenovationRewardInfo();
                }
                input.ReadMessage(RenovationRewardInfo);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  public sealed partial class RenovationStoreInfo : pb::IMessage<RenovationStoreInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RenovationStoreInfo> _parser = new pb::MessageParser<RenovationStoreInfo>(() => new RenovationStoreInfo());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RenovationStoreInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server.ServerRenovationReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RenovationStoreInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RenovationStoreInfo(RenovationStoreInfo other) : this() {
      _hasBits0 = other._hasBits0;
      storeConfigId_ = other.storeConfigId_;
      goodsConfigId_ = other.goodsConfigId_;
      storeType_ = other.storeType_;
      curExchangeNum_ = other.curExchangeNum_;
      maxExchangeNum_ = other.maxExchangeNum_;
      exchangeMaterials_ = other.exchangeMaterials_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RenovationStoreInfo Clone() {
      return new RenovationStoreInfo(this);
    }

    /// <summary>Field number for the "storeConfigId" field.</summary>
    public const int StoreConfigIdFieldNumber = 1;
    private readonly static string StoreConfigIdDefaultValue = "";

    private string storeConfigId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StoreConfigId {
      get { return storeConfigId_ ?? StoreConfigIdDefaultValue; }
      set {
        storeConfigId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "storeConfigId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStoreConfigId {
      get { return storeConfigId_ != null; }
    }
    /// <summary>Clears the value of the "storeConfigId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStoreConfigId() {
      storeConfigId_ = null;
    }

    /// <summary>Field number for the "goodsConfigId" field.</summary>
    public const int GoodsConfigIdFieldNumber = 2;
    private readonly static string GoodsConfigIdDefaultValue = "";

    private string goodsConfigId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GoodsConfigId {
      get { return goodsConfigId_ ?? GoodsConfigIdDefaultValue; }
      set {
        goodsConfigId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "goodsConfigId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGoodsConfigId {
      get { return goodsConfigId_ != null; }
    }
    /// <summary>Clears the value of the "goodsConfigId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGoodsConfigId() {
      goodsConfigId_ = null;
    }

    /// <summary>Field number for the "storeType" field.</summary>
    public const int StoreTypeFieldNumber = 3;
    private readonly static string StoreTypeDefaultValue = "";

    private string storeType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StoreType {
      get { return storeType_ ?? StoreTypeDefaultValue; }
      set {
        storeType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "storeType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStoreType {
      get { return storeType_ != null; }
    }
    /// <summary>Clears the value of the "storeType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStoreType() {
      storeType_ = null;
    }

    /// <summary>Field number for the "curExchangeNum" field.</summary>
    public const int CurExchangeNumFieldNumber = 4;
    private readonly static int CurExchangeNumDefaultValue = 0;

    private int curExchangeNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CurExchangeNum {
      get { if ((_hasBits0 & 1) != 0) { return curExchangeNum_; } else { return CurExchangeNumDefaultValue; } }
      set {
        _hasBits0 |= 1;
        curExchangeNum_ = value;
      }
    }
    /// <summary>Gets whether the "curExchangeNum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCurExchangeNum {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "curExchangeNum" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCurExchangeNum() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "maxExchangeNum" field.</summary>
    public const int MaxExchangeNumFieldNumber = 5;
    private readonly static int MaxExchangeNumDefaultValue = 0;

    private int maxExchangeNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxExchangeNum {
      get { if ((_hasBits0 & 2) != 0) { return maxExchangeNum_; } else { return MaxExchangeNumDefaultValue; } }
      set {
        _hasBits0 |= 2;
        maxExchangeNum_ = value;
      }
    }
    /// <summary>Gets whether the "maxExchangeNum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMaxExchangeNum {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "maxExchangeNum" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMaxExchangeNum() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "exchangeMaterials" field.</summary>
    public const int ExchangeMaterialsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Common.GoodsItem> _repeated_exchangeMaterials_codec
        = pb::FieldCodec.ForMessage(50, global::Common.GoodsItem.Parser);
    private readonly pbc::RepeatedField<global::Common.GoodsItem> exchangeMaterials_ = new pbc::RepeatedField<global::Common.GoodsItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Common.GoodsItem> ExchangeMaterials {
      get { return exchangeMaterials_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RenovationStoreInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RenovationStoreInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StoreConfigId != other.StoreConfigId) return false;
      if (GoodsConfigId != other.GoodsConfigId) return false;
      if (StoreType != other.StoreType) return false;
      if (CurExchangeNum != other.CurExchangeNum) return false;
      if (MaxExchangeNum != other.MaxExchangeNum) return false;
      if(!exchangeMaterials_.Equals(other.exchangeMaterials_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasStoreConfigId) hash ^= StoreConfigId.GetHashCode();
      if (HasGoodsConfigId) hash ^= GoodsConfigId.GetHashCode();
      if (HasStoreType) hash ^= StoreType.GetHashCode();
      if (HasCurExchangeNum) hash ^= CurExchangeNum.GetHashCode();
      if (HasMaxExchangeNum) hash ^= MaxExchangeNum.GetHashCode();
      hash ^= exchangeMaterials_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasStoreConfigId) {
        output.WriteRawTag(10);
        output.WriteString(StoreConfigId);
      }
      if (HasGoodsConfigId) {
        output.WriteRawTag(18);
        output.WriteString(GoodsConfigId);
      }
      if (HasStoreType) {
        output.WriteRawTag(26);
        output.WriteString(StoreType);
      }
      if (HasCurExchangeNum) {
        output.WriteRawTag(32);
        output.WriteInt32(CurExchangeNum);
      }
      if (HasMaxExchangeNum) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxExchangeNum);
      }
      exchangeMaterials_.WriteTo(output, _repeated_exchangeMaterials_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasStoreConfigId) {
        output.WriteRawTag(10);
        output.WriteString(StoreConfigId);
      }
      if (HasGoodsConfigId) {
        output.WriteRawTag(18);
        output.WriteString(GoodsConfigId);
      }
      if (HasStoreType) {
        output.WriteRawTag(26);
        output.WriteString(StoreType);
      }
      if (HasCurExchangeNum) {
        output.WriteRawTag(32);
        output.WriteInt32(CurExchangeNum);
      }
      if (HasMaxExchangeNum) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxExchangeNum);
      }
      exchangeMaterials_.WriteTo(ref output, _repeated_exchangeMaterials_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasStoreConfigId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StoreConfigId);
      }
      if (HasGoodsConfigId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GoodsConfigId);
      }
      if (HasStoreType) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StoreType);
      }
      if (HasCurExchangeNum) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurExchangeNum);
      }
      if (HasMaxExchangeNum) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxExchangeNum);
      }
      size += exchangeMaterials_.CalculateSize(_repeated_exchangeMaterials_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RenovationStoreInfo other) {
      if (other == null) {
        return;
      }
      if (other.HasStoreConfigId) {
        StoreConfigId = other.StoreConfigId;
      }
      if (other.HasGoodsConfigId) {
        GoodsConfigId = other.GoodsConfigId;
      }
      if (other.HasStoreType) {
        StoreType = other.StoreType;
      }
      if (other.HasCurExchangeNum) {
        CurExchangeNum = other.CurExchangeNum;
      }
      if (other.HasMaxExchangeNum) {
        MaxExchangeNum = other.MaxExchangeNum;
      }
      exchangeMaterials_.Add(other.exchangeMaterials_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            StoreConfigId = input.ReadString();
            break;
          }
          case 18: {
            GoodsConfigId = input.ReadString();
            break;
          }
          case 26: {
            StoreType = input.ReadString();
            break;
          }
          case 32: {
            CurExchangeNum = input.ReadInt32();
            break;
          }
          case 40: {
            MaxExchangeNum = input.ReadInt32();
            break;
          }
          case 50: {
            exchangeMaterials_.AddEntriesFrom(input, _repeated_exchangeMaterials_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            StoreConfigId = input.ReadString();
            break;
          }
          case 18: {
            GoodsConfigId = input.ReadString();
            break;
          }
          case 26: {
            StoreType = input.ReadString();
            break;
          }
          case 32: {
            CurExchangeNum = input.ReadInt32();
            break;
          }
          case 40: {
            MaxExchangeNum = input.ReadInt32();
            break;
          }
          case 50: {
            exchangeMaterials_.AddEntriesFrom(ref input, _repeated_exchangeMaterials_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExchangeRenovationStoreResult : pb::IMessage<ExchangeRenovationStoreResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExchangeRenovationStoreResult> _parser = new pb::MessageParser<ExchangeRenovationStoreResult>(() => new ExchangeRenovationStoreResult());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExchangeRenovationStoreResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server.ServerRenovationReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExchangeRenovationStoreResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExchangeRenovationStoreResult(ExchangeRenovationStoreResult other) : this() {
      _hasBits0 = other._hasBits0;
      code_ = other.code_;
      msg_ = other.msg_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExchangeRenovationStoreResult Clone() {
      return new ExchangeRenovationStoreResult(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private readonly static int CodeDefaultValue = 0;

    private int code_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { if ((_hasBits0 & 1) != 0) { return code_; } else { return CodeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        code_ = value;
      }
    }
    /// <summary>Gets whether the "code" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCode {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "code" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCode() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 2;
    private readonly static string MsgDefaultValue = "";

    private string msg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_ ?? MsgDefaultValue; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "msg" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMsg {
      get { return msg_ != null; }
    }
    /// <summary>Clears the value of the "msg" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMsg() {
      msg_ = null;
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private global::Server.RenovationStoreInfo data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Server.RenovationStoreInfo Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExchangeRenovationStoreResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExchangeRenovationStoreResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Msg != other.Msg) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCode) hash ^= Code.GetHashCode();
      if (HasMsg) hash ^= Msg.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCode) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (HasMsg) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCode) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (HasMsg) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCode) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (HasMsg) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExchangeRenovationStoreResult other) {
      if (other == null) {
        return;
      }
      if (other.HasCode) {
        Code = other.Code;
      }
      if (other.HasMsg) {
        Msg = other.Msg;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Server.RenovationStoreInfo();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::Server.RenovationStoreInfo();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::Server.RenovationStoreInfo();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ChooseRenovationResourceResult : pb::IMessage<ChooseRenovationResourceResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChooseRenovationResourceResult> _parser = new pb::MessageParser<ChooseRenovationResourceResult>(() => new ChooseRenovationResourceResult());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChooseRenovationResourceResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server.ServerRenovationReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChooseRenovationResourceResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChooseRenovationResourceResult(ChooseRenovationResourceResult other) : this() {
      _hasBits0 = other._hasBits0;
      code_ = other.code_;
      msg_ = other.msg_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChooseRenovationResourceResult Clone() {
      return new ChooseRenovationResourceResult(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private readonly static int CodeDefaultValue = 0;

    private int code_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { if ((_hasBits0 & 1) != 0) { return code_; } else { return CodeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        code_ = value;
      }
    }
    /// <summary>Gets whether the "code" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCode {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "code" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCode() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 2;
    private readonly static string MsgDefaultValue = "";

    private string msg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_ ?? MsgDefaultValue; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "msg" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMsg {
      get { return msg_ != null; }
    }
    /// <summary>Clears the value of the "msg" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMsg() {
      msg_ = null;
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private global::Server.RenovationTaskInfo data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Server.RenovationTaskInfo Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChooseRenovationResourceResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChooseRenovationResourceResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Msg != other.Msg) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCode) hash ^= Code.GetHashCode();
      if (HasMsg) hash ^= Msg.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCode) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (HasMsg) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCode) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (HasMsg) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCode) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (HasMsg) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChooseRenovationResourceResult other) {
      if (other == null) {
        return;
      }
      if (other.HasCode) {
        Code = other.Code;
      }
      if (other.HasMsg) {
        Msg = other.Msg;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Server.RenovationTaskInfo();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::Server.RenovationTaskInfo();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::Server.RenovationTaskInfo();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
