// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: train.server.worker.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Server {

  /// <summary>Holder for reflection information generated from train.server.worker.proto</summary>
  public static partial class TrainServerWorkerReflection {

    #region Descriptor
    /// <summary>File descriptor for train.server.worker.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TrainServerWorkerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chl0cmFpbi5zZXJ2ZXIud29ya2VyLnByb3RvEgZzZXJ2ZXIaG3RyYWluLnNl",
            "cnZlci5idWlsZGluZy5wcm90byK1AgoPVHJhaW5Xb3JrZXJJbmZvEhAKCHdv",
            "cmtlcklkGAEgASgJEg4KBnRvd25JZBgCIAEoCRIQCghjb25maWdJZBgDIAEo",
            "CRIUCgx3b3JrZXJOdW1iZXIYBCABKAUSEQoJYnVpZGluZ0lkGAUgASgJEgwK",
            "BG5hbWUYBiABKAkSDgoGZ2VuZGVyGAcgASgFEi8KCm9jY3VwYXRpb24YCCAB",
            "KA4yGy5zZXJ2ZXIuRW51bVRyYWluV29ya2VyVHlwZRINCgVsZXZlbBgJIAEo",
            "BRIUCgx1c2VCdWlkaW5nSUQYCiABKAkSDQoFc3RhdGUYCyABKAUSEgoKdXBn",
            "cmFkZVBvcxgMIAEoBRITCgt1cGdyYWRlVGltZRgNIAEoAxIZChF1cGdyYWRl",
            "RmluaXNoVGltZRgOIAEoAyJbChdUcmFpbkNoYW5nZVdvcmtlclJlc3VsdBIM",
            "CgRjb2RlGAEgAigFEgsKA21zZxgCIAIoCRIlCgRkYXRhGAMgASgLMhcuc2Vy",
            "dmVyLlRyYWluV29ya2VySW5mbyI+ChJUcmFpbldvcmtlckFsbEluZm8SKAoH",
            "d29ya2VycxgBIAMoCzIXLnNlcnZlci5UcmFpbldvcmtlckluZm8i2QEKG1Ry",
            "YWluV29ya2VyV29ya09yUmVzdFJlc3VsdBIMCgRjb2RlGAEgAigFEgsKA21z",
            "ZxgCIAIoCRI4CgRkYXRhGAMgASgLMiouc2VydmVyLlRyYWluV29ya2VyV29y",
            "a09yUmVzdFJlc3VsdC5SZXN1bHQaZQoGUmVzdWx0EisKCndvcmtlckluZm8Y",
            "ASACKAsyFy5zZXJ2ZXIuVHJhaW5Xb3JrZXJJbmZvEi4KC2J1aWRpbmdJbmZv",
            "GAIgAigLMhkuc2VydmVyLlRyYWluQnVpbGRpbmdJbmZvKjIKE0VudW1UcmFp",
            "bldvcmtlclR5cGUSCwoHRkFSTUlORxAAEg4KCklORFVTVFJJQUwQASpHChBU",
            "cmFpbldvcmtlclN0YXRlEgwKCFRXTk9STUFMEAASDwoLVFdVUEdSQURJTkcQ",
            "ARIUChBUV0ZJTklTSF9VUEdSQURFEAI="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Server.TrainServerBuildingReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Server.EnumTrainWorkerType), typeof(global::Server.TrainWorkerState), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Server.TrainWorkerInfo), global::Server.TrainWorkerInfo.Parser, new[]{ "WorkerId", "TownId", "ConfigId", "WorkerNumber", "BuidingId", "Name", "Gender", "Occupation", "Level", "UseBuidingID", "State", "UpgradePos", "UpgradeTime", "UpgradeFinishTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Server.TrainChangeWorkerResult), global::Server.TrainChangeWorkerResult.Parser, new[]{ "Code", "Msg", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Server.TrainWorkerAllInfo), global::Server.TrainWorkerAllInfo.Parser, new[]{ "Workers" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Server.TrainWorkerWorkOrRestResult), global::Server.TrainWorkerWorkOrRestResult.Parser, new[]{ "Code", "Msg", "Data" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Server.TrainWorkerWorkOrRestResult.Types.Result), global::Server.TrainWorkerWorkOrRestResult.Types.Result.Parser, new[]{ "WorkerInfo", "BuidingInfo" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///民工类型
  /// </summary>
  public enum EnumTrainWorkerType {
    /// <summary>
    ///农业
    /// </summary>
    [pbr::OriginalName("FARMING")] Farming = 0,
    /// <summary>
    ///工业
    /// </summary>
    [pbr::OriginalName("INDUSTRIAL")] Industrial = 1,
  }

  /// <summary>
  ///民工状态
  /// </summary>
  public enum TrainWorkerState {
    [pbr::OriginalName("TWNORMAL")] Twnormal = 0,
    [pbr::OriginalName("TWUPGRADING")] Twupgrading = 1,
    [pbr::OriginalName("TWFINISH_UPGRADE")] TwfinishUpgrade = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  ///民工信息
  /// </summary>
  public sealed partial class TrainWorkerInfo : pb::IMessage<TrainWorkerInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrainWorkerInfo> _parser = new pb::MessageParser<TrainWorkerInfo>(() => new TrainWorkerInfo());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrainWorkerInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server.TrainServerWorkerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainWorkerInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainWorkerInfo(TrainWorkerInfo other) : this() {
      _hasBits0 = other._hasBits0;
      workerId_ = other.workerId_;
      townId_ = other.townId_;
      configId_ = other.configId_;
      workerNumber_ = other.workerNumber_;
      buidingId_ = other.buidingId_;
      name_ = other.name_;
      gender_ = other.gender_;
      occupation_ = other.occupation_;
      level_ = other.level_;
      useBuidingID_ = other.useBuidingID_;
      state_ = other.state_;
      upgradePos_ = other.upgradePos_;
      upgradeTime_ = other.upgradeTime_;
      upgradeFinishTime_ = other.upgradeFinishTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainWorkerInfo Clone() {
      return new TrainWorkerInfo(this);
    }

    /// <summary>Field number for the "workerId" field.</summary>
    public const int WorkerIdFieldNumber = 1;
    private readonly static string WorkerIdDefaultValue = "";

    private string workerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WorkerId {
      get { return workerId_ ?? WorkerIdDefaultValue; }
      set {
        workerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "workerId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWorkerId {
      get { return workerId_ != null; }
    }
    /// <summary>Clears the value of the "workerId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWorkerId() {
      workerId_ = null;
    }

    /// <summary>Field number for the "townId" field.</summary>
    public const int TownIdFieldNumber = 2;
    private readonly static string TownIdDefaultValue = "";

    private string townId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TownId {
      get { return townId_ ?? TownIdDefaultValue; }
      set {
        townId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "townId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTownId {
      get { return townId_ != null; }
    }
    /// <summary>Clears the value of the "townId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTownId() {
      townId_ = null;
    }

    /// <summary>Field number for the "configId" field.</summary>
    public const int ConfigIdFieldNumber = 3;
    private readonly static string ConfigIdDefaultValue = "";

    private string configId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ConfigId {
      get { return configId_ ?? ConfigIdDefaultValue; }
      set {
        configId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "configId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasConfigId {
      get { return configId_ != null; }
    }
    /// <summary>Clears the value of the "configId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearConfigId() {
      configId_ = null;
    }

    /// <summary>Field number for the "workerNumber" field.</summary>
    public const int WorkerNumberFieldNumber = 4;
    private readonly static int WorkerNumberDefaultValue = 0;

    private int workerNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WorkerNumber {
      get { if ((_hasBits0 & 1) != 0) { return workerNumber_; } else { return WorkerNumberDefaultValue; } }
      set {
        _hasBits0 |= 1;
        workerNumber_ = value;
      }
    }
    /// <summary>Gets whether the "workerNumber" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWorkerNumber {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "workerNumber" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWorkerNumber() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "buidingId" field.</summary>
    public const int BuidingIdFieldNumber = 5;
    private readonly static string BuidingIdDefaultValue = "";

    private string buidingId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BuidingId {
      get { return buidingId_ ?? BuidingIdDefaultValue; }
      set {
        buidingId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "buidingId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBuidingId {
      get { return buidingId_ != null; }
    }
    /// <summary>Clears the value of the "buidingId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBuidingId() {
      buidingId_ = null;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 6;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 7;
    private readonly static int GenderDefaultValue = 0;

    private int gender_;
    /// <summary>
    ///性别
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Gender {
      get { if ((_hasBits0 & 2) != 0) { return gender_; } else { return GenderDefaultValue; } }
      set {
        _hasBits0 |= 2;
        gender_ = value;
      }
    }
    /// <summary>Gets whether the "gender" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGender {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "gender" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGender() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "occupation" field.</summary>
    public const int OccupationFieldNumber = 8;
    private readonly static global::Server.EnumTrainWorkerType OccupationDefaultValue = global::Server.EnumTrainWorkerType.Farming;

    private global::Server.EnumTrainWorkerType occupation_;
    /// <summary>
    ///职业
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Server.EnumTrainWorkerType Occupation {
      get { if ((_hasBits0 & 4) != 0) { return occupation_; } else { return OccupationDefaultValue; } }
      set {
        _hasBits0 |= 4;
        occupation_ = value;
      }
    }
    /// <summary>Gets whether the "occupation" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOccupation {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "occupation" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOccupation() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 9;
    private readonly static int LevelDefaultValue = 0;

    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { if ((_hasBits0 & 8) != 0) { return level_; } else { return LevelDefaultValue; } }
      set {
        _hasBits0 |= 8;
        level_ = value;
      }
    }
    /// <summary>Gets whether the "level" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLevel {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "level" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLevel() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "useBuidingID" field.</summary>
    public const int UseBuidingIDFieldNumber = 10;
    private readonly static string UseBuidingIDDefaultValue = "";

    private string useBuidingID_;
    /// <summary>
    ///建筑
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UseBuidingID {
      get { return useBuidingID_ ?? UseBuidingIDDefaultValue; }
      set {
        useBuidingID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "useBuidingID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUseBuidingID {
      get { return useBuidingID_ != null; }
    }
    /// <summary>Clears the value of the "useBuidingID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUseBuidingID() {
      useBuidingID_ = null;
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 11;
    private readonly static int StateDefaultValue = 0;

    private int state_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int State {
      get { if ((_hasBits0 & 16) != 0) { return state_; } else { return StateDefaultValue; } }
      set {
        _hasBits0 |= 16;
        state_ = value;
      }
    }
    /// <summary>Gets whether the "state" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasState {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "state" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearState() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "upgradePos" field.</summary>
    public const int UpgradePosFieldNumber = 12;
    private readonly static int UpgradePosDefaultValue = 0;

    private int upgradePos_;
    /// <summary>
    ///升级位置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int UpgradePos {
      get { if ((_hasBits0 & 32) != 0) { return upgradePos_; } else { return UpgradePosDefaultValue; } }
      set {
        _hasBits0 |= 32;
        upgradePos_ = value;
      }
    }
    /// <summary>Gets whether the "upgradePos" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUpgradePos {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "upgradePos" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUpgradePos() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "upgradeTime" field.</summary>
    public const int UpgradeTimeFieldNumber = 13;
    private readonly static long UpgradeTimeDefaultValue = 0L;

    private long upgradeTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UpgradeTime {
      get { if ((_hasBits0 & 64) != 0) { return upgradeTime_; } else { return UpgradeTimeDefaultValue; } }
      set {
        _hasBits0 |= 64;
        upgradeTime_ = value;
      }
    }
    /// <summary>Gets whether the "upgradeTime" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUpgradeTime {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "upgradeTime" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUpgradeTime() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "upgradeFinishTime" field.</summary>
    public const int UpgradeFinishTimeFieldNumber = 14;
    private readonly static long UpgradeFinishTimeDefaultValue = 0L;

    private long upgradeFinishTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UpgradeFinishTime {
      get { if ((_hasBits0 & 128) != 0) { return upgradeFinishTime_; } else { return UpgradeFinishTimeDefaultValue; } }
      set {
        _hasBits0 |= 128;
        upgradeFinishTime_ = value;
      }
    }
    /// <summary>Gets whether the "upgradeFinishTime" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUpgradeFinishTime {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "upgradeFinishTime" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUpgradeFinishTime() {
      _hasBits0 &= ~128;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrainWorkerInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrainWorkerInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WorkerId != other.WorkerId) return false;
      if (TownId != other.TownId) return false;
      if (ConfigId != other.ConfigId) return false;
      if (WorkerNumber != other.WorkerNumber) return false;
      if (BuidingId != other.BuidingId) return false;
      if (Name != other.Name) return false;
      if (Gender != other.Gender) return false;
      if (Occupation != other.Occupation) return false;
      if (Level != other.Level) return false;
      if (UseBuidingID != other.UseBuidingID) return false;
      if (State != other.State) return false;
      if (UpgradePos != other.UpgradePos) return false;
      if (UpgradeTime != other.UpgradeTime) return false;
      if (UpgradeFinishTime != other.UpgradeFinishTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasWorkerId) hash ^= WorkerId.GetHashCode();
      if (HasTownId) hash ^= TownId.GetHashCode();
      if (HasConfigId) hash ^= ConfigId.GetHashCode();
      if (HasWorkerNumber) hash ^= WorkerNumber.GetHashCode();
      if (HasBuidingId) hash ^= BuidingId.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (HasGender) hash ^= Gender.GetHashCode();
      if (HasOccupation) hash ^= Occupation.GetHashCode();
      if (HasLevel) hash ^= Level.GetHashCode();
      if (HasUseBuidingID) hash ^= UseBuidingID.GetHashCode();
      if (HasState) hash ^= State.GetHashCode();
      if (HasUpgradePos) hash ^= UpgradePos.GetHashCode();
      if (HasUpgradeTime) hash ^= UpgradeTime.GetHashCode();
      if (HasUpgradeFinishTime) hash ^= UpgradeFinishTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasWorkerId) {
        output.WriteRawTag(10);
        output.WriteString(WorkerId);
      }
      if (HasTownId) {
        output.WriteRawTag(18);
        output.WriteString(TownId);
      }
      if (HasConfigId) {
        output.WriteRawTag(26);
        output.WriteString(ConfigId);
      }
      if (HasWorkerNumber) {
        output.WriteRawTag(32);
        output.WriteInt32(WorkerNumber);
      }
      if (HasBuidingId) {
        output.WriteRawTag(42);
        output.WriteString(BuidingId);
      }
      if (HasName) {
        output.WriteRawTag(50);
        output.WriteString(Name);
      }
      if (HasGender) {
        output.WriteRawTag(56);
        output.WriteInt32(Gender);
      }
      if (HasOccupation) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Occupation);
      }
      if (HasLevel) {
        output.WriteRawTag(72);
        output.WriteInt32(Level);
      }
      if (HasUseBuidingID) {
        output.WriteRawTag(82);
        output.WriteString(UseBuidingID);
      }
      if (HasState) {
        output.WriteRawTag(88);
        output.WriteInt32(State);
      }
      if (HasUpgradePos) {
        output.WriteRawTag(96);
        output.WriteInt32(UpgradePos);
      }
      if (HasUpgradeTime) {
        output.WriteRawTag(104);
        output.WriteInt64(UpgradeTime);
      }
      if (HasUpgradeFinishTime) {
        output.WriteRawTag(112);
        output.WriteInt64(UpgradeFinishTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasWorkerId) {
        output.WriteRawTag(10);
        output.WriteString(WorkerId);
      }
      if (HasTownId) {
        output.WriteRawTag(18);
        output.WriteString(TownId);
      }
      if (HasConfigId) {
        output.WriteRawTag(26);
        output.WriteString(ConfigId);
      }
      if (HasWorkerNumber) {
        output.WriteRawTag(32);
        output.WriteInt32(WorkerNumber);
      }
      if (HasBuidingId) {
        output.WriteRawTag(42);
        output.WriteString(BuidingId);
      }
      if (HasName) {
        output.WriteRawTag(50);
        output.WriteString(Name);
      }
      if (HasGender) {
        output.WriteRawTag(56);
        output.WriteInt32(Gender);
      }
      if (HasOccupation) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Occupation);
      }
      if (HasLevel) {
        output.WriteRawTag(72);
        output.WriteInt32(Level);
      }
      if (HasUseBuidingID) {
        output.WriteRawTag(82);
        output.WriteString(UseBuidingID);
      }
      if (HasState) {
        output.WriteRawTag(88);
        output.WriteInt32(State);
      }
      if (HasUpgradePos) {
        output.WriteRawTag(96);
        output.WriteInt32(UpgradePos);
      }
      if (HasUpgradeTime) {
        output.WriteRawTag(104);
        output.WriteInt64(UpgradeTime);
      }
      if (HasUpgradeFinishTime) {
        output.WriteRawTag(112);
        output.WriteInt64(UpgradeFinishTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasWorkerId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WorkerId);
      }
      if (HasTownId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TownId);
      }
      if (HasConfigId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConfigId);
      }
      if (HasWorkerNumber) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WorkerNumber);
      }
      if (HasBuidingId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BuidingId);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasGender) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gender);
      }
      if (HasOccupation) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Occupation);
      }
      if (HasLevel) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (HasUseBuidingID) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UseBuidingID);
      }
      if (HasState) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(State);
      }
      if (HasUpgradePos) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UpgradePos);
      }
      if (HasUpgradeTime) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UpgradeTime);
      }
      if (HasUpgradeFinishTime) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UpgradeFinishTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrainWorkerInfo other) {
      if (other == null) {
        return;
      }
      if (other.HasWorkerId) {
        WorkerId = other.WorkerId;
      }
      if (other.HasTownId) {
        TownId = other.TownId;
      }
      if (other.HasConfigId) {
        ConfigId = other.ConfigId;
      }
      if (other.HasWorkerNumber) {
        WorkerNumber = other.WorkerNumber;
      }
      if (other.HasBuidingId) {
        BuidingId = other.BuidingId;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasGender) {
        Gender = other.Gender;
      }
      if (other.HasOccupation) {
        Occupation = other.Occupation;
      }
      if (other.HasLevel) {
        Level = other.Level;
      }
      if (other.HasUseBuidingID) {
        UseBuidingID = other.UseBuidingID;
      }
      if (other.HasState) {
        State = other.State;
      }
      if (other.HasUpgradePos) {
        UpgradePos = other.UpgradePos;
      }
      if (other.HasUpgradeTime) {
        UpgradeTime = other.UpgradeTime;
      }
      if (other.HasUpgradeFinishTime) {
        UpgradeFinishTime = other.UpgradeFinishTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            WorkerId = input.ReadString();
            break;
          }
          case 18: {
            TownId = input.ReadString();
            break;
          }
          case 26: {
            ConfigId = input.ReadString();
            break;
          }
          case 32: {
            WorkerNumber = input.ReadInt32();
            break;
          }
          case 42: {
            BuidingId = input.ReadString();
            break;
          }
          case 50: {
            Name = input.ReadString();
            break;
          }
          case 56: {
            Gender = input.ReadInt32();
            break;
          }
          case 64: {
            Occupation = (global::Server.EnumTrainWorkerType) input.ReadEnum();
            break;
          }
          case 72: {
            Level = input.ReadInt32();
            break;
          }
          case 82: {
            UseBuidingID = input.ReadString();
            break;
          }
          case 88: {
            State = input.ReadInt32();
            break;
          }
          case 96: {
            UpgradePos = input.ReadInt32();
            break;
          }
          case 104: {
            UpgradeTime = input.ReadInt64();
            break;
          }
          case 112: {
            UpgradeFinishTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            WorkerId = input.ReadString();
            break;
          }
          case 18: {
            TownId = input.ReadString();
            break;
          }
          case 26: {
            ConfigId = input.ReadString();
            break;
          }
          case 32: {
            WorkerNumber = input.ReadInt32();
            break;
          }
          case 42: {
            BuidingId = input.ReadString();
            break;
          }
          case 50: {
            Name = input.ReadString();
            break;
          }
          case 56: {
            Gender = input.ReadInt32();
            break;
          }
          case 64: {
            Occupation = (global::Server.EnumTrainWorkerType) input.ReadEnum();
            break;
          }
          case 72: {
            Level = input.ReadInt32();
            break;
          }
          case 82: {
            UseBuidingID = input.ReadString();
            break;
          }
          case 88: {
            State = input.ReadInt32();
            break;
          }
          case 96: {
            UpgradePos = input.ReadInt32();
            break;
          }
          case 104: {
            UpgradeTime = input.ReadInt64();
            break;
          }
          case 112: {
            UpgradeFinishTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///民工操作结果
  /// </summary>
  public sealed partial class TrainChangeWorkerResult : pb::IMessage<TrainChangeWorkerResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrainChangeWorkerResult> _parser = new pb::MessageParser<TrainChangeWorkerResult>(() => new TrainChangeWorkerResult());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrainChangeWorkerResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server.TrainServerWorkerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainChangeWorkerResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainChangeWorkerResult(TrainChangeWorkerResult other) : this() {
      _hasBits0 = other._hasBits0;
      code_ = other.code_;
      msg_ = other.msg_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainChangeWorkerResult Clone() {
      return new TrainChangeWorkerResult(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private readonly static int CodeDefaultValue = 0;

    private int code_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { if ((_hasBits0 & 1) != 0) { return code_; } else { return CodeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        code_ = value;
      }
    }
    /// <summary>Gets whether the "code" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCode {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "code" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCode() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 2;
    private readonly static string MsgDefaultValue = "";

    private string msg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_ ?? MsgDefaultValue; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "msg" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMsg {
      get { return msg_ != null; }
    }
    /// <summary>Clears the value of the "msg" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMsg() {
      msg_ = null;
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private global::Server.TrainWorkerInfo data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Server.TrainWorkerInfo Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrainChangeWorkerResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrainChangeWorkerResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Msg != other.Msg) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCode) hash ^= Code.GetHashCode();
      if (HasMsg) hash ^= Msg.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCode) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (HasMsg) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCode) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (HasMsg) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCode) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (HasMsg) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrainChangeWorkerResult other) {
      if (other == null) {
        return;
      }
      if (other.HasCode) {
        Code = other.Code;
      }
      if (other.HasMsg) {
        Msg = other.Msg;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Server.TrainWorkerInfo();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::Server.TrainWorkerInfo();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::Server.TrainWorkerInfo();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///民工所有信息
  /// </summary>
  public sealed partial class TrainWorkerAllInfo : pb::IMessage<TrainWorkerAllInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrainWorkerAllInfo> _parser = new pb::MessageParser<TrainWorkerAllInfo>(() => new TrainWorkerAllInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrainWorkerAllInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server.TrainServerWorkerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainWorkerAllInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainWorkerAllInfo(TrainWorkerAllInfo other) : this() {
      workers_ = other.workers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainWorkerAllInfo Clone() {
      return new TrainWorkerAllInfo(this);
    }

    /// <summary>Field number for the "workers" field.</summary>
    public const int WorkersFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Server.TrainWorkerInfo> _repeated_workers_codec
        = pb::FieldCodec.ForMessage(10, global::Server.TrainWorkerInfo.Parser);
    private readonly pbc::RepeatedField<global::Server.TrainWorkerInfo> workers_ = new pbc::RepeatedField<global::Server.TrainWorkerInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Server.TrainWorkerInfo> Workers {
      get { return workers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrainWorkerAllInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrainWorkerAllInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!workers_.Equals(other.workers_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= workers_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      workers_.WriteTo(output, _repeated_workers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      workers_.WriteTo(ref output, _repeated_workers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += workers_.CalculateSize(_repeated_workers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrainWorkerAllInfo other) {
      if (other == null) {
        return;
      }
      workers_.Add(other.workers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            workers_.AddEntriesFrom(input, _repeated_workers_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            workers_.AddEntriesFrom(ref input, _repeated_workers_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///民工入驻操作结果
  /// </summary>
  public sealed partial class TrainWorkerWorkOrRestResult : pb::IMessage<TrainWorkerWorkOrRestResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrainWorkerWorkOrRestResult> _parser = new pb::MessageParser<TrainWorkerWorkOrRestResult>(() => new TrainWorkerWorkOrRestResult());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrainWorkerWorkOrRestResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server.TrainServerWorkerReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainWorkerWorkOrRestResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainWorkerWorkOrRestResult(TrainWorkerWorkOrRestResult other) : this() {
      _hasBits0 = other._hasBits0;
      code_ = other.code_;
      msg_ = other.msg_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainWorkerWorkOrRestResult Clone() {
      return new TrainWorkerWorkOrRestResult(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private readonly static int CodeDefaultValue = 0;

    private int code_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { if ((_hasBits0 & 1) != 0) { return code_; } else { return CodeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        code_ = value;
      }
    }
    /// <summary>Gets whether the "code" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCode {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "code" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCode() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 2;
    private readonly static string MsgDefaultValue = "";

    private string msg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_ ?? MsgDefaultValue; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "msg" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMsg {
      get { return msg_ != null; }
    }
    /// <summary>Clears the value of the "msg" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMsg() {
      msg_ = null;
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private global::Server.TrainWorkerWorkOrRestResult.Types.Result data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Server.TrainWorkerWorkOrRestResult.Types.Result Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrainWorkerWorkOrRestResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrainWorkerWorkOrRestResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Msg != other.Msg) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCode) hash ^= Code.GetHashCode();
      if (HasMsg) hash ^= Msg.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCode) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (HasMsg) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCode) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (HasMsg) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCode) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (HasMsg) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrainWorkerWorkOrRestResult other) {
      if (other == null) {
        return;
      }
      if (other.HasCode) {
        Code = other.Code;
      }
      if (other.HasMsg) {
        Msg = other.Msg;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Server.TrainWorkerWorkOrRestResult.Types.Result();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::Server.TrainWorkerWorkOrRestResult.Types.Result();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::Server.TrainWorkerWorkOrRestResult.Types.Result();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the TrainWorkerWorkOrRestResult message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class Result : pb::IMessage<Result>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Result> _parser = new pb::MessageParser<Result>(() => new Result());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Result> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Server.TrainWorkerWorkOrRestResult.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Result() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Result(Result other) : this() {
          workerInfo_ = other.workerInfo_ != null ? other.workerInfo_.Clone() : null;
          buidingInfo_ = other.buidingInfo_ != null ? other.buidingInfo_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Result Clone() {
          return new Result(this);
        }

        /// <summary>Field number for the "workerInfo" field.</summary>
        public const int WorkerInfoFieldNumber = 1;
        private global::Server.TrainWorkerInfo workerInfo_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Server.TrainWorkerInfo WorkerInfo {
          get { return workerInfo_; }
          set {
            workerInfo_ = value;
          }
        }

        /// <summary>Field number for the "buidingInfo" field.</summary>
        public const int BuidingInfoFieldNumber = 2;
        private global::Server.TrainBuildingInfo buidingInfo_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Server.TrainBuildingInfo BuidingInfo {
          get { return buidingInfo_; }
          set {
            buidingInfo_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Result);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Result other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(WorkerInfo, other.WorkerInfo)) return false;
          if (!object.Equals(BuidingInfo, other.BuidingInfo)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (workerInfo_ != null) hash ^= WorkerInfo.GetHashCode();
          if (buidingInfo_ != null) hash ^= BuidingInfo.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (workerInfo_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(WorkerInfo);
          }
          if (buidingInfo_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(BuidingInfo);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (workerInfo_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(WorkerInfo);
          }
          if (buidingInfo_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(BuidingInfo);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (workerInfo_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(WorkerInfo);
          }
          if (buidingInfo_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(BuidingInfo);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Result other) {
          if (other == null) {
            return;
          }
          if (other.workerInfo_ != null) {
            if (workerInfo_ == null) {
              WorkerInfo = new global::Server.TrainWorkerInfo();
            }
            WorkerInfo.MergeFrom(other.WorkerInfo);
          }
          if (other.buidingInfo_ != null) {
            if (buidingInfo_ == null) {
              BuidingInfo = new global::Server.TrainBuildingInfo();
            }
            BuidingInfo.MergeFrom(other.BuidingInfo);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (workerInfo_ == null) {
                  WorkerInfo = new global::Server.TrainWorkerInfo();
                }
                input.ReadMessage(WorkerInfo);
                break;
              }
              case 18: {
                if (buidingInfo_ == null) {
                  BuidingInfo = new global::Server.TrainBuildingInfo();
                }
                input.ReadMessage(BuidingInfo);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (workerInfo_ == null) {
                  WorkerInfo = new global::Server.TrainWorkerInfo();
                }
                input.ReadMessage(WorkerInfo);
                break;
              }
              case 18: {
                if (buidingInfo_ == null) {
                  BuidingInfo = new global::Server.TrainBuildingInfo();
                }
                input.ReadMessage(BuidingInfo);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
